import { SvgIcon } from "./components/svg/SvgIcon";
import {
  HomeView,
  AboutView,
  ComponentsView,
  ComponentsAccordionView,
  ComponentsAlertView,
  ComponentsAudioView,
  ComponentsBadgeView,
  ComponentsBreadcrumbView,
  ComponentsButtonView,
  ComponentsCardView,
  ComponentsTabsView,
  ComponentsVideoView,
  ContactView,
} from "./views";

export const PagesData = [
  {
    id: "1",
    url: "/",
    title: "Home",
    hideNav: true,
    content: HomeView,
  },
  {
    id: "2",
    url: "/components",
    title: "Components",
    content: ComponentsView,
  },
  {
    id: "2-1",
    url: "/components/accordion",
    title: "Accordion",
    hideNav: true,
    theme: "pink",
    content: ComponentsAccordionView,
  },
  {
    id: "2-2",
    url: "/components/alert",
    title: "Alert",
    hideNav: true,
    theme: "blue",
    content: ComponentsAlertView,
  },
  {
    id: "2-3",
    url: "/components/audio",
    title: "Audio",
    hideNav: true,
    theme: "green",
    content: ComponentsAudioView,
  },
  {
    id: "2-4",
    url: "/components/badge",
    title: "Badge",
    hideNav: true,
    theme: "purple",
    content: ComponentsBadgeView,
  },
  {
    id: "2-5",
    url: "/components/breadcrumb",
    title: "Breadcrumb",
    hideNav: true,
    theme: "purple",
    content: ComponentsBreadcrumbView,
  },
  {
    id: "2-6",
    url: "/components/button",
    title: "Button",
    hideNav: true,
    theme: "red",
    content: ComponentsButtonView,
  },
  {
    id: "2-7",
    url: "/components/card",
    title: "Card",
    hideNav: true,
    theme: "orange",
    content: ComponentsCardView,
  },
  {
    id: "2-8",
    url: "/components/tabs",
    title: "Tabs",
    hideNav: true,
    theme: "orange",
    content: ComponentsTabsView,
  },
  {
    id: "2-9",
    url: "/components/video",
    title: "Video",
    hideNav: true,
    theme: "orange",
    content: ComponentsVideoView,
  },
  {
    id: "3",
    url: "/about",
    title: "About",
    content: AboutView,
  },
  {
    id: "4",
    url: "/contact",
    title: "Contact",
    content: ContactView,
  },
];
